### ISSUE TITLE
Cleaning up CSS

### ISSUE THREAD

**Issue by tspeed90** [fac-14/teamcoolerweek1#38]
It might be ideal if you made a class for all the profiles, since they are all very similar apart from the background image and you just add the background image separately using the id of each person as you have. Just a way to avoid too repetition.

Suggestion:
```
.members {
   width: 100%;
   height: 30vh;
 }

  #armand {
   background-image: url("img/armand.jpg");
  }

  #nathalie {
    background-image: url("img/nathalie.jpg");
    grid-column-start: 2;
  }

  #kate {
    background-image: url("img/kate.jpg");
  }

  #joe {
   background-image: url("img/joe.jpg");  
  } 
```
https://github.com/fac-14/teamcoolerweek1/blob/master/style.css#L425-L448

**Comment by Zeanort** [comment]
Thanks for the suggestion! It has been implemented :)

**Comment by njons** [comment]
Added a class for making all sections 90vh instead of setting sizes for all ids
