### ISSUE TITLE
Leftover headshot images commented out

### ISSUE THREAD

**Issue by martingaston** [fac-14/teamcoolerweek1#39]
Can probably remove the commented HTML before we push to production :100: 

Push to production, that sounds pretty legit right? 

https://github.com/fac-14/teamcoolerweek1/blob/7a22487b526158ad0745a177d2b7a43e2f8ef3ee/index.html#L72

https://github.com/fac-14/teamcoolerweek1/blob/7a22487b526158ad0745a177d2b7a43e2f8ef3ee/index.html#L82

https://github.com/fac-14/teamcoolerweek1/blob/7a22487b526158ad0745a177d2b7a43e2f8ef3ee/index.html#L96

https://github.com/fac-14/teamcoolerweek1/blob/7a22487b526158ad0745a177d2b7a43e2f8ef3ee/index.html#L107

**Comment by sbinlondon** [comment]
Done 💥
