### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by tspeed90** [fac-14/teamcoolerweek1#45]
Since your photos aren't in image tags, I'd suggest looking into aria-labels to make sure screen readers are able to access information about the images on the page. In this line: 
```
<article class="background-image" id="armand">
```
(and all the other articles with images in them) you could add an aria-label so that the screen reader would tell users what was in the article. :smile:

Aria-labels: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute
or more specifically: https://www.w3.org/WAI/GL/wiki/ARIATechnique_usingImgRole_with_aria-label_forCSS-backgroundImage

**Comment by sbinlondon** [comment]
Thanks for raising and also leaving info. I've added `role="img"` and `aria-label=""` to each article that uses a photo as a background image 😊
