### ISSUE TITLE
Contact us form thrown off on mobile

### ISSUE THREAD

**Issue by martingaston** [fac-14/teamcoolerweek1#51]
99% sure you guys are aware, but the contact box goes a little funky when the screen size gets low: 

![image](https://user-images.githubusercontent.com/35241716/42372993-928302b2-810b-11e8-9c11-c32093f3770b.png)

Screenshot from Firefox responsive mode, also tested on the latest version of Chrome on Android.

**Comment by sbinlondon** [comment]
Thanks for letting us know the browser info - we're on it! 💪
